name: build

on:
  push:
    branches: [pf-master]
  pull_request:
    branches: [pf-master]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
    steps:
      - uses: actions/checkout@v2
      - name: clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: test --all-features
        run: cargo test --all-features
      - name: Setup minio
        run: |
          docker run -d -p 9000:9000 --name minio \
                     -e "MINIO_ACCESS_KEY=$AWS_ACCESS_KEY_ID" \
                     -e "MINIO_SECRET_KEY=$AWS_SECRET_ACCESS_KEY" \
                     -v /tmp/data:/data \
                     -v /tmp/config:/root/.minio \
                     minio/minio server /data

          export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
          export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
          export AWS_EC2_METADATA_DISABLED=true

          aws --endpoint-url http://127.0.0.1:9000/ s3 mb s3://testbucket

      - name: test --ignored
        run: cargo test -- --ignored